version: "3.7"

services:
  api:
    build:
      context: .
      network: host
    environment:
      DATABASE_URL: "postgres://quizzes:quizzes@postgres:5432/quizzes"
      # This PLAY_HTTP_SECRET_KEY is only used in docker-compose and is different to the one used on
      # Heroku
      PLAY_HTTP_SECRET_KEY: "3oO>nb4L5p4n4kj8Pt^Wjvo0]2Z0oyP1tUtzM[Y1A8<nv3^n>;1i`e`p<]5U7qEX"
    image: "cw-quizzes-api"
    links:
      - postgres
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  flyway:
    image: boxfuse/flyway:5.2.4-alpine
    command: -url=jdbc:postgresql://postgres:5432/quizzes -user=quizzes -password=quizzes migrate
    volumes:
      - .:/flyway/sql

  postgres:
    environment:
      POSTGRES_DB: "quizzes"
      POSTGRES_PASSWORD: "quizzes"
      POSTGRES_USER: "quizzes"
    image: postgres:11-alpine
    ports:
      - "5432:5432"